#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
#dubbo配置
dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
#目标是让该模块读取到配置信息
tanhua:
#默认推荐列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88
  sms:
    signName:
    templateCode:
    accessKey:
    secret:
  oss:
    accessKey:
    secret:
    endpoint:
    bucketName:
    url:
  aip:
    appId:
    apiKey:
    secretKey:
#  huanxin:
#    url:
#    orgName:
#    appName:
#    clientId:
#    clientSecret:
  huanxin:
    appkey:
    clientId:
    clientSecret:
logging:
  level:
    com:
      easemob:
        im:
          http=debug:
          shaded:
            io:
              netty=error: