#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
#dubbo配置
dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
#目标是让该模块读取到配置信息
tanhua:
#默认推荐列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88
  sms:
    signName:
    templateCode:
    accessKey:
    secret:
  oss:
    accessKey:
    secret:
    endpoint:
    bucketName:
    url:
  aip:
    appId:
    apiKey:
    secretKey:
#  huanxin:
#    url:
#    orgName:
#    appName:
#    clientId:
#    clientSecret:
  huanxin:
    appkey:
    clientId:
    clientSecret:
logging:
  level:
    com:
      easemob:
        im:
          http=debug:
          shaded:
            io:
              netty=error:
# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个，客户端访问首先访问tracker,访问到之后进行文件上传,上传完成要进行浏览器http访问，再拿nginx地址拼接，nginx地址+上传完成返回的地址=访问地址
  tracker-list: 192.168.136.160:22122
  web-server-url: http://192.168.136.160:8888/
  #配置文件上传的大小
Spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB