server:
  port: 8888
spring:
  application:
    name: tanhua-gateway
  profiles:
    active: prod
  cloud:
    nacos:
      #注册中心
      discovery:
        server-addr: 192.168.136.160:8848
#跨域支持
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
#路由配置
      routes:
        # 手机端访问
#-id:当前路由的唯一标识、uri: 路由的目标微服务地址(nacos上的服务列表的服务名)、predicates:断言、按照路径匹配的规则--即用户只要访问/app/**都会分发到lb://tanhua-app-server
        - id: tanhua-app-server
          uri: lb://tanhua-app-server
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix= 1
        # 管理后台
        - id: tanhua-admin
          uri: lb://tanhua-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1
#自定义配置，定义不需要校验token的连接
gateway:
  excludedUrls: /user/login,/user/loginVerification,/system/users/verification,/system/users/login